services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example

  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db